# Generated by Django 3.0.7 on 2020-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='summary',
            new_name='title',
        ),
    ]
